apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: hello-world
  namespace: test-app
spec:
  hosts:
  - "hello.localhost"
  gateways:
  - istio-system/main-gateway
  http:
  - route:
    - destination:
        host: hello-world
        port:
          number: 80
