apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: meshwiki
  namespace: meshwiki
spec:
  hosts:
  - "wiki.localhost"
  gateways:
  - istio-system/main-gateway
  http:
  - route:
    - destination:
        host: meshwiki
        port:
          number: 80
