apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: graphwiki
  namespace: graphwiki
spec:
  hosts:
  - "wiki.localhost"
  gateways:
  - istio-system/main-gateway
  http:
  - route:
    - destination:
        host: graphwiki
        port:
          number: 80
